export const data = [
  {
    id: 1,
    fullName: "John Doe",
    gender: "Male",
    contact: "+91-9876543210",
    email: "johndoe@example.com",
    college: "ABC Engineering College",
    department: "Computer Science",
    year: 3,
    studentID: "CSE20230123",
    courses: ["Data Structures", "Web Development"],
    gpa: 8.5,
  },
  {
    id: 2,
    fullName: "Jane Smith",
    gender: "Female",
    contact: "+91-9876543220",
    email: "janesmith@example.com",
    college: "XYZ University",
    department: "Mechanical Engineering",
    year: 2,
    studentID: "ME20220110",
    courses: ["Thermodynamics", "Fluid Mechanics"],
    gpa: 7.9,
  },
  {
    id: 3,
    fullName: "Aryan Patel",
    gender: "Male",
    contact: "+91-9876543230",
    email: "aryanpatel@example.com",
    college: "LMN Institute",
    department: "Electronics",
    year: 1,
    studentID: "EL20240155",
    courses: ["Circuit Theory", "Microprocessors"],
    gpa: 8.2,
  },
  {
    id: 4,
    fullName: "Priya Sharma",
    gender: "Female",
    contact: "+91-9876543240",
    email: "priyasharma@example.com",
    college: "DEF College",
    department: "Biotechnology",
    year: 4,
    studentID: "BT20200188",
    courses: ["Genetics", "Bioprocess Engineering"],
    gpa: 8.6,
  },
  {
    id: 5,
    fullName: "Rahul Verma",
    gender: "Male",
    contact: "+91-9876543250",
    email: "rahulverma@example.com",
    college: "PQR University",
    department: "Civil Engineering",
    year: 3,
    studentID: "CE20230277",
    courses: ["Structural Analysis", "Geotechnical Engineering"],
    gpa: 7.8,
  },
  {
    id: 6,
    fullName: "Sneha Iyer",
    gender: "Female",
    contact: "+91-9876543260",
    email: "snehaiyer@example.com",
    college: "UVW Institute",
    department: "Architecture",
    year: 2,
    studentID: "AR20220265",
    courses: ["Design Fundamentals", "Urban Planning"],
    gpa: 8.4,
  },
  {
    id: 7,
    fullName: "Vikas Rao",
    gender: "Male",
    contact: "+91-9876543270",
    email: "vikasrao@example.com",
    college: "GHI College",
    department: "Information Technology",
    year: 1,
    studentID: "IT20240176",
    courses: ["Data Science", "Cybersecurity"],
    gpa: 8.7,
  },
  {
    id: 8,
    fullName: "Neha Kapoor",
    gender: "Female",
    contact: "+91-9876543280",
    email: "nehakapoor@example.com",
    college: "MNO University",
    department: "Physics",
    year: 4,
    studentID: "PH20200190",
    courses: ["Quantum Mechanics", "Electrodynamics"],
    gpa: 8.3,
  },
  {
    id: 9,
    fullName: "Amit Mehta",
    gender: "Male",
    contact: "+91-9876543290",
    email: "amitmehta@example.com",
    college: "STU Institute",
    department: "Chemical Engineering",
    year: 3,
    studentID: "CH20230285",
    courses: ["Process Control", "Thermodynamics"],
    gpa: 7.6,
  },
  {
    id: 10,
    fullName: "Riya Sen",
    gender: "Female",
    contact: "+91-9876543300",
    email: "riyasen@example.com",
    college: "JKL College",
    department: "Mathematics",
    year: 2,
    studentID: "MA20220281",
    courses: ["Linear Algebra", "Probability"],
    gpa: 8.1,
  },
  {
    id: 11,
    fullName: "Kabir Singh",
    gender: "Male",
    contact: "+91-9876543310",
    email: "kabirsingh@example.com",
    college: "ABC Engineering College",
    department: "Computer Science",
    year: 2,
    studentID: "CSE20220245",
    courses: ["Algorithms", "Cloud Computing"],
    gpa: 8.2,
  },
  {
    id: 12,
    fullName: "Meera Joshi",
    gender: "Female",
    contact: "+91-9876543320",
    email: "meerajoshi@example.com",
    college: "XYZ University",
    department: "Electrical Engineering",
    year: 3,
    studentID: "EE20230210",
    courses: ["Power Systems", "Embedded Systems"],
    gpa: 8.0,
  },
  {
    id: 13,
    fullName: "Aditya Rao",
    gender: "Male",
    contact: "+91-9876543330",
    email: "adityarao@example.com",
    college: "LMN Institute",
    department: "Aerospace Engineering",
    year: 4,
    studentID: "AE20200150",
    courses: ["Aerodynamics", "Satellite Technology"],
    gpa: 8.5,
  },
  {
    id: 14,
    fullName: "Ananya Das",
    gender: "Female",
    contact: "+91-9876543340",
    email: "ananyadas@example.com",
    college: "DEF College",
    department: "Environmental Science",
    year: 1,
    studentID: "ES20240180",
    courses: ["Climate Change", "Sustainable Development"],
    gpa: 8.7,
  },
  {
    id: 15,
    fullName: "Rohit Menon",
    gender: "Male",
    contact: "+91-9876543350",
    email: "rohitmenon@example.com",
    college: "PQR University",
    department: "Mechanical Engineering",
    year: 3,
    studentID: "ME20230295",
    courses: ["CAD Design", "Heat Transfer"],
    gpa: 7.8,
  },
  {
    id: 16,
    fullName: "Ishita Kapoor",
    gender: "Female",
    contact: "+91-9876543360",
    email: "ishitakapoor@example.com",
    college: "UVW Institute",
    department: "Robotics",
    year: 2,
    studentID: "RB20220260",
    courses: ["AI in Robotics", "Automation"],
    gpa: 8.4,
  },
  {
    id: 17,
    fullName: "Karan Malhotra",
    gender: "Male",
    contact: "+91-9876543370",
    email: "karanmalhotra@example.com",
    college: "GHI College",
    department: "Finance",
    year: 1,
    studentID: "FN20240175",
    courses: ["Stock Market", "Risk Management"],
    gpa: 8.1,
  },
  {
    id: 18,
    fullName: "Aisha Khan",
    gender: "Female",
    contact: "+91-9876543380",
    email: "aishakhan@example.com",
    college: "MNO University",
    department: "Psychology",
    year: 4,
    studentID: "PS20200185",
    courses: ["Cognitive Science", "Behavioral Therapy"],
    gpa: 8.3,
  },
  {
    id: 19,
    fullName: "Yash Sharma",
    gender: "Male",
    contact: "+91-9876543390",
    email: "yashsharma@example.com",
    college: "STU Institute",
    department: "Journalism",
    year: 3,
    studentID: "JN20230290",
    courses: ["Media Ethics", "Investigative Reporting"],
    gpa: 7.9,
  },
  {
    id: 20,
    fullName: "Mira Arora",
    gender: "Female",
    contact: "+91-9876543400",
    email: "mirarora@example.com",
    college: "JKL College",
    department: "Medicine",
    year: 2,
    studentID: "MD20220278",
    courses: ["Human Anatomy", "Pharmacology"],
    gpa: 8.6,
  },
  {
    id: 21,
    fullName: "Sahil Gupta",
    gender: "Male",
    contact: "+91-9876543410",
    email: "sahilgupta@example.com",
    college: "ABC Engineering College",
    department: "Computer Science",
    year: 1,
    studentID: "CSE20240112",
    courses: ["Programming Fundamentals", "Data Structures"],
    gpa: 8.3,
  },
  {
    id: 22,
    fullName: "Rhea Kapoor",
    gender: "Female",
    contact: "+91-9876543420",
    email: "rheakapoor@example.com",
    college: "XYZ University",
    department: "Economics",
    year: 4,
    studentID: "EC20200134",
    courses: ["Macroeconomics", "Microeconomics"],
    gpa: 8.1,
  },
  {
    id: 23,
    fullName: "Ishaan Verma",
    gender: "Male",
    contact: "+91-9876543430",
    email: "ishaanverma@example.com",
    college: "LMN Institute",
    department: "Physics",
    year: 2,
    studentID: "PH20220222",
    courses: ["Electrodynamics", "Quantum Mechanics"],
    gpa: 8.6,
  },
  {
    id: 24,
    fullName: "Alia Sharma",
    gender: "Female",
    contact: "+91-9876543440",
    email: "aliasharma@example.com",
    college: "DEF College",
    department: "Biotechnology",
    year: 3,
    studentID: "BT20230202",
    courses: ["Genetics", "Biochemical Engineering"],
    gpa: 7.9,
  },
  {
    id: 25,
    fullName: "Kunal Mehta",
    gender: "Male",
    contact: "+91-9876543450",
    email: "kunalmehta@example.com",
    college: "PQR University",
    department: "Electrical Engineering",
    year: 1,
    studentID: "EE20240150",
    courses: ["Circuit Theory", "Power Systems"],
    gpa: 8.2,
  },
  {
    id: 26,
    fullName: "Tanya Bajpai",
    gender: "Female",
    contact: "+91-9876543460",
    email: "tanyabajpai@example.com",
    college: "UVW Institute",
    department: "Psychology",
    year: 4,
    studentID: "PS20200167",
    courses: ["Behavioral Neuroscience", "Clinical Psychology"],
    gpa: 8.4,
  },
  {
    id: 27,
    fullName: "Rajesh Nair",
    gender: "Male",
    contact: "+91-9876543470",
    email: "rajeshnair@example.com",
    college: "GHI College",
    department: "Aerospace Engineering",
    year: 2,
    studentID: "AE20220289",
    courses: ["Aerodynamics", "Aircraft Structures"],
    gpa: 8.0,
  },
  {
    id: 28,
    fullName: "Simran Kaur",
    gender: "Female",
    contact: "+91-9876543480",
    email: "simrankaur@example.com",
    college: "MNO University",
    department: "Finance",
    year: 3,
    studentID: "FN20230280",
    courses: ["Investment Banking", "Risk Analysis"],
    gpa: 8.5,
  },
  {
    id: 29,
    fullName: "Arjun Das",
    gender: "Male",
    contact: "+91-9876543490",
    email: "arjundas@example.com",
    college: "STU Institute",
    department: "Mechanical Engineering",
    year: 1,
    studentID: "ME20240155",
    courses: ["Thermodynamics", "Fluid Mechanics"],
    gpa: 7.7,
  },
  {
    id: 30,
    fullName: "Pooja Reddy",
    gender: "Female",
    contact: "+91-9876543500",
    email: "poojareddy@example.com",
    college: "JKL College",
    department: "Mathematics",
    year: 2,
    studentID: "MA20220290",
    courses: ["Linear Algebra", "Probability"],
    gpa: 8.3,
  },
  {
    id: 31,
    fullName: "Varun Yadav",
    gender: "Male",
    contact: "+91-9876543510",
    email: "varunyadav@example.com",
    college: "ABC Engineering College",
    department: "Computer Science",
    year: 2,
    studentID: "CSE20220250",
    courses: ["Algorithms", "Cloud Computing"],
    gpa: 8.1,
  },
  {
    id: 32,
    fullName: "Sanya Bhatia",
    gender: "Female",
    contact: "+91-9876543520",
    email: "sanyabhatia@example.com",
    college: "XYZ University",
    department: "Mechanical Engineering",
    year: 3,
    studentID: "ME20230220",
    courses: ["CAD Design", "Thermodynamics"],
    gpa: 7.8,
  },
  {
    id: 33,
    fullName: "Kartik Rao",
    gender: "Male",
    contact: "+91-9876543530",
    email: "kartikrao@example.com",
    college: "LMN Institute",
    department: "Electrical Engineering",
    year: 1,
    studentID: "EE20240175",
    courses: ["Power Systems", "Microcontrollers"],
    gpa: 8.3,
  },
  {
    id: 34,
    fullName: "Aditi Singh",
    gender: "Female",
    contact: "+91-9876543540",
    email: "aditisingh@example.com",
    college: "DEF College",
    department: "Biotechnology",
    year: 4,
    studentID: "BT20200195",
    courses: ["Genetics", "Bioprocess Engineering"],
    gpa: 8.5,
  },
  {
    id: 35,
    fullName: "Rohan Kapoor",
    gender: "Male",
    contact: "+91-9876543550",
    email: "rohankapoor@example.com",
    college: "PQR University",
    department: "Civil Engineering",
    year: 2,
    studentID: "CE20220285",
    courses: ["Structural Analysis", "Geotechnical Engineering"],
    gpa: 7.9,
  },
  {
    id: 36,
    fullName: "Tara Iyer",
    gender: "Female",
    contact: "+91-9876543560",
    email: "taraiyer@example.com",
    college: "UVW Institute",
    department: "Architecture",
    year: 3,
    studentID: "AR20230275",
    courses: ["Design Fundamentals", "Urban Planning"],
    gpa: 8.4,
  },
  {
    id: 37,
    fullName: "Vikram Sharma",
    gender: "Male",
    contact: "+91-9876543570",
    email: "vikramsharma@example.com",
    college: "GHI College",
    department: "Information Technology",
    year: 1,
    studentID: "IT20240188",
    courses: ["Data Science", "Cybersecurity"],
    gpa: 8.7,
  },
  {
    id: 38,
    fullName: "Neha Agarwal",
    gender: "Female",
    contact: "+91-9876543580",
    email: "nehaagarwal@example.com",
    college: "MNO University",
    department: "Physics",
    year: 4,
    studentID: "PH20200197",
    courses: ["Quantum Mechanics", "Electrodynamics"],
    gpa: 8.2,
  },
  {
    id: 39,
    fullName: "Manish Mehta",
    gender: "Male",
    contact: "+91-9876543590",
    email: "manishmehta@example.com",
    college: "STU Institute",
    department: "Chemical Engineering",
    year: 3,
    studentID: "CH20230295",
    courses: ["Process Control", "Thermodynamics"],
    gpa: 7.6,
  },
  {
    id: 40,
    fullName: "Riya Sen",
    gender: "Female",
    contact: "+91-9876543600",
    email: "riyasen@example.com",
    college: "JKL College",
    department: "Mathematics",
    year: 2,
    studentID: "MA20220295",
    courses: ["Linear Algebra", "Probability"],
    gpa: 8.1,
  },
  {
    id: 61,
    fullName: "Dev Mishra",
    gender: "Male",
    contact: "+91-9876543610",
    email: "devmishra@example.com",
    college: "ABC Engineering College",
    department: "Computer Science",
    year: 3,
    studentID: "CSE20230165",
    courses: ["Machine Learning", "Data Structures"],
    gpa: 8.6,
  },
  {
    id: 62,
    fullName: "Aarushi Jain",
    gender: "Female",
    contact: "+91-9876543620",
    email: "aarushijain@example.com",
    college: "XYZ University",
    department: "Mechanical Engineering",
    year: 2,
    studentID: "ME20220235",
    courses: ["Fluid Mechanics", "Thermodynamics"],
    gpa: 7.8,
  },
  {
    id: 63,
    fullName: "Rohan Chatterjee",
    gender: "Male",
    contact: "+91-9876543630",
    email: "rohanchatterjee@example.com",
    college: "LMN Institute",
    department: "Electrical Engineering",
    year: 1,
    studentID: "EE20240188",
    courses: ["Circuit Theory", "Power Systems"],
    gpa: 8.3,
  },
  {
    id: 64,
    fullName: "Sneha Mukherjee",
    gender: "Female",
    contact: "+91-9876543640",
    email: "snehamukherjee@example.com",
    college: "DEF College",
    department: "Biotechnology",
    year: 4,
    studentID: "BT20200210",
    courses: ["Genetics", "Biochemical Engineering"],
    gpa: 8.5,
  },
  {
    id: 65,
    fullName: "Amit Khanna",
    gender: "Male",
    contact: "+91-9876543650",
    email: "amitkhanna@example.com",
    college: "PQR University",
    department: "Civil Engineering",
    year: 2,
    studentID: "CE20220292",
    courses: ["Structural Analysis", "Geotechnical Engineering"],
    gpa: 7.9,
  },
  {
    id: 66,
    fullName: "Natasha Nair",
    gender: "Female",
    contact: "+91-9876543660",
    email: "natashanair@example.com",
    college: "UVW Institute",
    department: "Architecture",
    year: 3,
    studentID: "AR20230285",
    courses: ["Design Fundamentals", "Urban Planning"],
    gpa: 8.4,
  },
  {
    id: 67,
    fullName: "Vikram Malhotra",
    gender: "Male",
    contact: "+91-9876543670",
    email: "vikrammalhotra@example.com",
    college: "GHI College",
    department: "Information Technology",
    year: 1,
    studentID: "IT20240192",
    courses: ["Data Science", "Cybersecurity"],
    gpa: 8.7,
  },
  {
    id: 68,
    fullName: "Neha Reddy",
    gender: "Female",
    contact: "+91-9876543680",
    email: "nehareddy@example.com",
    college: "MNO University",
    department: "Physics",
    year: 4,
    studentID: "PH20200205",
    courses: ["Quantum Mechanics", "Electrodynamics"],
    gpa: 8.2,
  },
  {
    id: 69,
    fullName: "Rajeev Mehta",
    gender: "Male",
    contact: "+91-9876543690",
    email: "rajeevmehta@example.com",
    college: "STU Institute",
    department: "Chemical Engineering",
    year: 3,
    studentID: "CH20230302",
    courses: ["Process Control", "Thermodynamics"],
    gpa: 7.6,
  },
  {
    id: 70,
    fullName: "Riya Gupta",
    gender: "Female",
    contact: "+91-9876543700",
    email: "riyagupta@example.com",
    college: "JKL College",
    department: "Mathematics",
    year: 2,
    studentID: "MA20220298",
    courses: ["Linear Algebra", "Probability"],
    gpa: 8.1,
  },
];
